### PR TITLE
refactor: introduce task version directory structure

### PR DESCRIPTION
**Pull request by pchila**
Restructure tasks directories to allow for easier versioning.
Simplify Task names (cc @agrimmer )

### CODE REVIEW

**Review by christian-kreuzberger-dtx — CHANGES_REQUESTED** [review]
everything looks good, but let's wait with merging this until we have confirmation from @agrimmer regarding the task name changes

**Comment by pchila** [comment]
Comparison between old and new pipeline yaml 
[azurepipeline_new.yaml.txt](https://github.com/keptn-sandbox/keptn-azure-devops-extension/files/8177050/azurepipeline_new.yaml.txt)
[azurepipeline_old.yaml.txt](https://github.com/keptn-sandbox/keptn-azure-devops-extension/files/8177052/azurepipeline_old.yaml.txt)

**Comment by pchila** [comment]
@christian-kreuzberger-dtx as agreed, I reintroduced `Keptn` in the task names and directories, please have another look...

**Review by christian-kreuzberger-dtx — APPROVED** [review]
LGTM

**Pull request merged**
